name: ${project.name}
version: ${project.version}
main: ${main.class}
author: ${author}
api-version: 1.13

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

softdepend: [AuthMe, BanManager, BungeeChatAPI, CMI, DiscordSRV, Factions, Feudal, ItemsAdder, Essentials, LegacyFactions, Lands, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, mcMMO, Nicky, PlaceholderAPI, ProtocolLib, SimpleClans, Towny, TownyChat, Vault, WorldEdit]

commands:

permissions:
  AirdropX.create:
    default: op
  AirdropX.edit:
    default: op
  AirdropX.call:
    default: op
  AirdropX.remove:
    default: op
  AirdropX.listall:
    default: op
  AirdropX.callatplayer:
    default: op
  AirdropX.bypass.delay:
    default: false
  AirdropX.bypass.opening_delay:
    default: false
  AirdropX.crashfixer:
    default: op
  AirdropX.compass:
    default: op